from .resume import UpdateResumeView, CreateResumeView, ResumesIndexView,DeleteResumeView, ResumeUpdateDateView, ResumePublicView
from .education import AddEducationView,EditEducationView, DeleteEducationView
from .experience import AddExperienceView,EditExperienceView, DeleteExperienceView