from .resume import UpdateResumeView, CreateResumeView, ResumesIndexView,ResumeDetailView,DeleteResumeView, ResumeUpdateDateView, ResumePublicView, ResumeListView
from .education import AddEducationView,EditEducationView, DeleteEducationView
from .experience import AddExperienceView,EditExperienceView, DeleteExperienceView