# Generated by Django 4.1.3 on 2022-11-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Фото'),
        ),
    ]
