# Generated by Django 4.1.3 on 2022-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='photo/default.jpeg', null=True, upload_to='photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='account',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
