# Generated by Django 4.1.3 on 2022-11-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_message_options_alter_response_options_and_more'),
        ('accounts', '0007_alter_account_description_alter_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='respond_vacancies',
            field=models.ManyToManyField(related_name='applicants', through='main.Response', to='main.vacancy', verbose_name='Вакансии'),
        ),
    ]
