# Generated by Django 4.1.3 on 2022-11-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_resume_email_alter_resume_facebook_and_more'),
        ('accounts', '0009_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='respond_vacancies',
            field=models.ManyToManyField(related_name='applicants', through='main.Response', to='main.vacancy', verbose_name='Вакансии, на которые откликнулся'),
        ),
    ]
