# Generated by Django 4.1.3 on 2022-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_response_applicant_response_author'),
        ('accounts', '0010_alter_account_respond_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='respond_resumes',
            field=models.ManyToManyField(related_name='employers', through='main.Response', to='main.resume', verbose_name='Резюме, на которые откликнулся'),
        ),
    ]
