# Generated by Django 4.1.3 on 2022-11-12 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(null=True, verbose_name='Желаемая зарплата')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('vacancy_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='main.vacancycategory', verbose_name='Категория вакансии')),
            ],
        ),
    ]
