# Generated by Django 4.1.3 on 2022-11-12 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_resume_options_alter_vacancycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duties',
            field=models.TextField(verbose_name='Обязанности'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField(null=True, verbose_name='Зарплата')),
                ('description', models.TextField(null=True)),
                ('experience_time', models.PositiveIntegerField(null=True, verbose_name='Опыт работы(лет)')),
                ('is_public', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('vacancy_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='main.vacancycategory', verbose_name='Категория вакансии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
