# Generated by Django 4.1.3 on 2022-11-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_resume_is_public_alter_resume_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='is_public',
            field=models.BooleanField(null=True),
        ),
    ]
