# Generated by Django 4.1.3 on 2022-11-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_resume_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AddField(
            model_name='resume',
            name='facebook',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='resume',
            name='telegram',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
