# Generated by Django 4.1.3 on 2022-11-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_resume_email_alter_resume_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='telegram',
        ),
    ]
